{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clientApp.fullname" . }}
data:
{{- toYaml (index .Values.configMap.data .Values.env) | nindent 2 }}
{{- end }}
